apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastfood-product-management-mysql-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
