server:
  port: 8080

spring:
  datasource:
    drive-class-name: org.h2.Driver
    username: "sa"
    password: "sa"
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1

  jpa:
    hibernate:
      ddl-auto: create-drop

  logging:
    level:
      root: ERROR
      org.springframework: ERROR