server:
  port: 8081

spring:
  datasource:
    drive-class-name: com.mysql.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:}
    url: jdbc:mysql://${MYSQL_HOST:localhost:3306}/product_management_db

  jpa:
    hibernate:
      ddl-auto: create-drop

  logging:
    level:
      root: ERROR
      org.springframework: ERROR